"""Module level enum variables for generated migrations

Enums that are created or dropped inside migration can be defined once as module level variables
and then reused by upgrade and downgrade functions instead of being repeated in every operation.
"""

import keyword
import logging
import os
import re
from typing import Any, Callable, Dict, Iterable, Optional, Tuple, Union

import sqlalchemy
from alembic import util
from alembic.autogenerate.api import AutogenContext
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory

from alembic_postgresql_enum.configuration import get_configuration

log = logging.getLogger(f"alembic.{__name__}")

POSTGRESQL_IMPORT = "from sqlalchemy.dialects import postgresql"

# Comments around definitions, similar to ones alembic puts around generated operations
ENUM_DEFINITIONS_HEADER = "# ### enums auto generated by alembic-postgresql-enum ###"
ENUM_DEFINITIONS_FOOTER = "# ### end enums ###"

# Name of template variable that can be used to choose where enums are defined
TEMPLATE_VARIABLE_NAME = "enums"
# Indentation of the line that uses template variable is captured to indent definitions with it
TEMPLATE_VARIABLE_PATTERN = re.compile(r"^([ \t]*).*?\$\{\s*" + TEMPLATE_VARIABLE_NAME + r"\b", re.MULTILINE)

# Names that are already taken inside generated migration file
RESERVED_NAMES = frozenset(
    (
        "op",
        "sa",
        "postgresql",
        "revision",
        "down_revision",
        "branch_labels",
        "depends_on",
        "upgrade",
        "downgrade",
        "Sequence",
        "Union",
        "ColumnType",
        "TableReference",
        "TableIndex",
    )
)


def to_valid_identifier(value: str) -> str:
    """Convert given string into a valid python identifier"""
    result = re.sub(r"[^0-9a-zA-Z_]", "_", value)
    if not result or result[0].isdigit():
        result = f"_{result}"
    if keyword.iskeyword(result) or result in RESERVED_NAMES:
        result = f"{result}_enum"
    return result


class EnumDefinitionsBlock(str):
    """Block of module level enum definitions

    Alembic renders ${imports} section of migration template as "\\n".join(sorted(imports)),
    so this string is always sorted last to be placed after all imports it depends on.
    """

    def __lt__(self, other):
        return False

    def __le__(self, other):
        return str.__eq__(self, other)

    def __gt__(self, other):
        return not str.__eq__(self, other)

    def __ge__(self, other):
        return True


class EnumVariables:
    """Variable names of enums that are created or dropped inside currently generated migration"""

    def __init__(self) -> None:
        self._default_schema: Optional[str] = None
        self._variable_names: Dict[Tuple[str, str], str] = {}
        self._definitions: Dict[str, str] = {}
        self._rendered_into_template = False

    def reset(self, default_schema: str) -> None:
        """Forget everything that was collected for previously generated migration"""
        self._default_schema = default_schema
        self._variable_names = {}
        self._definitions = {}
        self._rendered_into_template = False

    def register(self, schema: str, name: str, enum_values: Iterable[str]) -> str:
        """Reserve variable name for given enum"""
        if (schema, name) in self._variable_names:
            return self._variable_names[(schema, name)]

        get_variable_name = get_configuration().enum_variable_name
        variable_name = to_valid_identifier(get_variable_name(self._external_schema(schema), name))

        taken_names = set(self._variable_names.values())
        if variable_name in taken_names:
            suffix = 2
            while f"{variable_name}_{suffix}" in taken_names:
                suffix += 1
            variable_name = f"{variable_name}_{suffix}"

        self._variable_names[(schema, name)] = variable_name
        self._definitions[variable_name] = self._render_definition(variable_name, schema, name, enum_values)
        return variable_name

    def get(self, schema: Optional[str], name: Optional[str]) -> Optional[str]:
        """Variable name of given enum or None if it is not defined at module level"""
        if name is None:
            return None
        if schema is None:
            schema = self._default_schema
        return self._variable_names.get((schema, name))

    def place_definitions(self, migration_context: MigrationContext) -> None:
        """Put enum definitions into ${enums} section of migration template if it has one

        Otherwise they are rendered into ${imports} section, see add_definitions_to_imports.
        """
        self._rendered_into_template = False
        if not self._definitions:
            return

        template_args = migration_context.opts.get("template_args")
        if template_args is None:
            return

        indentation = self._template_variable_indentation(template_args)
        if indentation is None:
            return

        # mako indents only the first line of rendered value, so the rest is indented here
        template_args[TEMPLATE_VARIABLE_NAME] = self._definitions_block().replace("\n", f"\n{indentation}")
        self._rendered_into_template = True

    def add_definitions_to_imports(self, autogen_context: AutogenContext) -> None:
        """Make definitions and everything they need available inside generated migration"""
        imports = autogen_context.imports
        imports.add(POSTGRESQL_IMPORT)

        if self._rendered_into_template:
            return

        # imports are cleared by alembic for every generated migration file, so block is added on every render
        imports.add(EnumDefinitionsBlock("\n" + self._definitions_block()))

    def _definitions_block(self) -> str:
        definitions = (definition for _, definition in sorted(self._definitions.items()))
        return "\n".join((ENUM_DEFINITIONS_HEADER, *definitions, ENUM_DEFINITIONS_FOOTER))

    def _render_definition(self, variable_name: str, schema: str, name: str, enum_values: Iterable[str]) -> str:
        arguments = [repr(value) for value in enum_values]
        arguments.append(f"name={name!r}")
        if schema != self._default_schema:
            arguments.append(f"schema={schema!r}")
        arguments.append("create_type=False")

        return f"{variable_name} = postgresql.ENUM({', '.join(arguments)})"

    def _template_variable_indentation(self, template_args: Dict[str, Any]) -> Optional[str]:
        """Indentation of ${enums} inside migration template, None if template does not use it"""
        config = template_args.get("config")
        if config is None:
            return None

        try:
            script_directory = ScriptDirectory.from_config(config)
            with open(os.path.join(str(script_directory.dir), "script.py.mako"), encoding="utf-8") as template_file:
                template = template_file.read()
        except (OSError, util.CommandError) as error:
            log.info("Migration template is not available, enums will be defined among imports: %r", error)
            return None

        indentations = TEMPLATE_VARIABLE_PATTERN.findall(template)
        if not indentations:
            return None

        if len(set(indentations)) > 1:
            log.warning(
                "${%s} is used with different indentation inside migration template, %r is used for all of them",
                TEMPLATE_VARIABLE_NAME,
                indentations[0],
            )

        return indentations[0]

    def _external_schema(self, schema: str) -> Optional[str]:
        """Schema as it is seen by user configuration, None for enums of default schema"""
        if schema == self._default_schema:
            return None
        return schema


enum_variables = EnumVariables()


class EnumVariableRenderItem:
    """Renders enums that are defined at module level as their variable names

    Alembic renders types by their repr prefixed with dialect name, so repr of enum is not enough
    to replace type with variable name, render_item hook is used instead.
    """

    def __init__(self, original_render_item: Optional[Callable[..., Any]]):
        self.original_render_item = original_render_item

    def __call__(self, type_: str, object_: Any, autogen_context: AutogenContext) -> Union[str, bool]:
        if type_ == "type" and isinstance(object_, sqlalchemy.Enum):
            variable_name = enum_variables.get(object_.schema, object_.name)
            if variable_name is not None:
                return variable_name

        if self.original_render_item is not None:
            return self.original_render_item(type_, object_, autogen_context)
        return False


def use_enum_variables_while_rendering(autogen_context: AutogenContext) -> None:
    """Make alembic render module level enums as their variable names"""
    original_render_item = autogen_context.opts.get("render_item")
    if isinstance(original_render_item, EnumVariableRenderItem):
        return
    autogen_context.opts["render_item"] = EnumVariableRenderItem(original_render_item)
