from typing import TYPE_CHECKING, Any, Dict, Optional, Sequence

from alembic import autogenerate
from alembic.config import Config as AlembicConfig
from mako.template import Template
from sqlalchemy import Column, Integer, MetaData, Table
from sqlalchemy.dialects import postgresql

import alembic_postgresql_enum
from alembic_postgresql_enum import Config
from alembic_postgresql_enum.configuration import get_configuration
from alembic_postgresql_enum.enum_variables import (
    ENUM_DEFINITIONS_FOOTER,
    ENUM_DEFINITIONS_HEADER,
)
from tests.base.run_migration_test_abc import CompareAndRunTestCase
from tests.utils.migration_context import create_migration_context

if TYPE_CHECKING:
    from sqlalchemy import Connection

POSTGRESQL_IMPORT = "from sqlalchemy.dialects import postgresql"


def definitions_block(*definitions: str) -> str:
    """Enum definitions as they are rendered into generated migration"""
    return "\n".join((ENUM_DEFINITIONS_HEADER, *definitions, ENUM_DEFINITIONS_FOOTER))


def expected_imports(*definitions: str, other_imports: Sequence[str] = ()) -> str:
    """Imports section of generated migration with enum definitions at the end of it"""
    imports = sorted((POSTGRESQL_IMPORT, *other_imports))
    return "\n".join((*imports, "", definitions_block(*definitions)))


from tests.schemas import (
    CAR_COLORS_COLUMN_NAME,
    CAR_COLORS_ENUM_NAME,
    CAR_TABLE_NAME,
    USER_STATUS_COLUMN_NAME,
    USER_STATUS_ENUM_NAME,
    USER_TABLE_NAME,
    get_car_schema_without_enum,
    get_schema_with_enum_in_array_variants,
    get_schema_with_enum_variants,
    get_schema_without_enum,
)


class TestModuleLevelEnumOnCreateTable(CompareAndRunTestCase):
    """Check that created enum is defined once as module level variable and reused by both functions"""

    config = Config(module_level_enums=True)

    new_enum_variants = ["active", "passive"]

    def get_database_schema(self) -> MetaData:
        return MetaData()

    def get_target_schema(self) -> MetaData:
        return get_schema_with_enum_variants(self.new_enum_variants)

    def get_expected_imports(self) -> Optional[str]:
        return expected_imports(
            f"{USER_STATUS_ENUM_NAME} = postgresql.ENUM('active', 'passive',"
            f" name='{USER_STATUS_ENUM_NAME}', create_type=False)"
        )

    def get_expected_upgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        {USER_STATUS_ENUM_NAME}.create(op.get_bind())
        op.create_table('{USER_TABLE_NAME}',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('{USER_STATUS_COLUMN_NAME}', {USER_STATUS_ENUM_NAME}, nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('{USER_TABLE_NAME}')
        {USER_STATUS_ENUM_NAME}.drop(op.get_bind())
        # ### end Alembic commands ###
        """


class TestModuleLevelEnumOnAddColumnWithArray(CompareAndRunTestCase):
    """Check that module level enum variable is reused inside ARRAY column"""

    config = Config(module_level_enums=True)

    new_enum_variants = ["black", "white", "red"]

    def get_database_schema(self) -> MetaData:
        return get_car_schema_without_enum()

    def get_target_schema(self) -> MetaData:
        return get_schema_with_enum_in_array_variants(self.new_enum_variants)

    def get_expected_imports(self) -> Optional[str]:
        return expected_imports(
            f"{CAR_COLORS_ENUM_NAME} = postgresql.ENUM({', '.join(map(repr, self.new_enum_variants))},"
            f" name='{CAR_COLORS_ENUM_NAME}', create_type=False)"
        )

    def get_expected_upgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        {CAR_COLORS_ENUM_NAME}.create(op.get_bind())
        op.add_column('{CAR_TABLE_NAME}', sa.Column('{CAR_COLORS_COLUMN_NAME}', postgresql.ARRAY({CAR_COLORS_ENUM_NAME}), nullable=True))
        # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('{CAR_TABLE_NAME}', '{CAR_COLORS_COLUMN_NAME}')
        {CAR_COLORS_ENUM_NAME}.drop(op.get_bind())
        # ### end Alembic commands ###
        """


class TestModuleLevelEnumOnDropEnum(CompareAndRunTestCase):
    """Check that enum dropped on upgrade is defined at module level as well"""

    config = Config(module_level_enums=True)

    enum_variants_to_delete = ["active", "passive"]

    def get_database_schema(self) -> MetaData:
        return get_schema_with_enum_variants(self.enum_variants_to_delete)

    def get_target_schema(self) -> MetaData:
        return get_schema_without_enum()

    def get_expected_imports(self) -> Optional[str]:
        return expected_imports(
            f"{USER_STATUS_ENUM_NAME} = postgresql.ENUM('active', 'passive',"
            f" name='{USER_STATUS_ENUM_NAME}', create_type=False)"
        )

    def get_expected_upgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('{USER_TABLE_NAME}', '{USER_STATUS_COLUMN_NAME}')
        {USER_STATUS_ENUM_NAME}.drop(op.get_bind())
        # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> str:
        # For some reason alembic decided to add redundant autoincrement=False on downgrade
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        {USER_STATUS_ENUM_NAME}.create(op.get_bind())
        op.add_column('{USER_TABLE_NAME}', sa.Column('{USER_STATUS_COLUMN_NAME}', {USER_STATUS_ENUM_NAME}, autoincrement=False, nullable=True))
        # ### end Alembic commands ###
        """


class TestModuleLevelEnumInsideNewSchema(CompareAndRunTestCase):
    """Check that variable name of enum outside of default schema is prefixed with its schema"""

    config = Config(module_level_enums=True)
    disable_running = True

    new_enum_variants = ["active", "passive"]
    non_existing_schema = "non_existing_schema"

    def get_database_schema(self) -> MetaData:
        return MetaData()

    def get_target_schema(self) -> MetaData:
        target_schema = MetaData(schema=self.non_existing_schema)
        Table(
            USER_TABLE_NAME,
            target_schema,
            Column("id", Integer, primary_key=True),
            Column(
                USER_STATUS_COLUMN_NAME,
                postgresql.ENUM(*self.new_enum_variants, name=USER_STATUS_ENUM_NAME, metadata=target_schema),
            ),
        )
        return target_schema

    def get_expected_imports(self) -> Optional[str]:
        return expected_imports(
            f"{self.non_existing_schema}_{USER_STATUS_ENUM_NAME} = postgresql.ENUM('active', 'passive',"
            f" name='{USER_STATUS_ENUM_NAME}', schema='{self.non_existing_schema}', create_type=False)"
        )

    def get_expected_upgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        {self.non_existing_schema}_{USER_STATUS_ENUM_NAME}.create(op.get_bind())
        op.create_table('{USER_TABLE_NAME}',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('{USER_STATUS_COLUMN_NAME}', {self.non_existing_schema}_{USER_STATUS_ENUM_NAME}, nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='{self.non_existing_schema}'
        )
        # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('{USER_TABLE_NAME}', schema='{self.non_existing_schema}')
        {self.non_existing_schema}_{USER_STATUS_ENUM_NAME}.drop(op.get_bind())
        # ### end Alembic commands ###
        """


class TestModuleLevelEnumWithExoticName(CompareAndRunTestCase):
    """Check that enum name that is not a valid python identifier is converted into one"""

    config = Config(module_level_enums=True)

    enum_name = "user-status"
    new_enum_variants = ["active", "passive"]

    def get_database_schema(self) -> MetaData:
        return MetaData()

    def get_target_schema(self) -> MetaData:
        target_schema = MetaData()
        Table(
            USER_TABLE_NAME,
            target_schema,
            Column("id", Integer, primary_key=True),
            Column(
                USER_STATUS_COLUMN_NAME,
                postgresql.ENUM(*self.new_enum_variants, name=self.enum_name),
            ),
        )
        return target_schema

    def get_expected_imports(self) -> Optional[str]:
        return expected_imports(
            f"user_status = postgresql.ENUM('active', 'passive', name='{self.enum_name}', create_type=False)"
        )

    def get_expected_upgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        user_status.create(op.get_bind())
        op.create_table('{USER_TABLE_NAME}',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('{USER_STATUS_COLUMN_NAME}', user_status, nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('{USER_TABLE_NAME}')
        user_status.drop(op.get_bind())
        # ### end Alembic commands ###
        """


class TestModuleLevelEnumWithCustomVariableName(CompareAndRunTestCase):
    """Check that variable names are taken from configuration and are made unique"""

    config = Config(module_level_enums=True, enum_variable_name=lambda schema, name: "enum")

    user_status_variants = ["active", "passive"]
    car_colors_variants = ["black", "white"]

    def get_database_schema(self) -> MetaData:
        return get_car_schema_without_enum()

    def get_target_schema(self) -> MetaData:
        target_schema = MetaData()
        Table(
            USER_TABLE_NAME,
            target_schema,
            Column("id", Integer, primary_key=True),
            Column(
                USER_STATUS_COLUMN_NAME,
                postgresql.ENUM(*self.user_status_variants, name=USER_STATUS_ENUM_NAME),
            ),
        )
        Table(
            CAR_TABLE_NAME,
            target_schema,
            Column("id", Integer, primary_key=True),
            Column(
                CAR_COLORS_COLUMN_NAME,
                postgresql.ENUM(*self.car_colors_variants, name=CAR_COLORS_ENUM_NAME),
            ),
        )
        return target_schema

    def get_expected_imports(self) -> Optional[str]:
        return expected_imports(
            f"enum = postgresql.ENUM('black', 'white', name='{CAR_COLORS_ENUM_NAME}', create_type=False)",
            f"enum_2 = postgresql.ENUM('active', 'passive', name='{USER_STATUS_ENUM_NAME}', create_type=False)",
        )

    def get_expected_upgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        enum.create(op.get_bind())
        enum_2.create(op.get_bind())
        op.create_table('{USER_TABLE_NAME}',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('{USER_STATUS_COLUMN_NAME}', enum_2, nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.add_column('{CAR_TABLE_NAME}', sa.Column('{CAR_COLORS_COLUMN_NAME}', enum, nullable=True))
        # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('{CAR_TABLE_NAME}', '{CAR_COLORS_COLUMN_NAME}')
        op.drop_table('{USER_TABLE_NAME}')
        enum_2.drop(op.get_bind())
        enum.drop(op.get_bind())
        # ### end Alembic commands ###
        """


class TestModuleLevelEnumWithSyncEnumValues(CompareAndRunTestCase):
    """Check that enum definitions are rendered after imports they depend on"""

    config = Config(module_level_enums=True)

    old_user_status_variants = ["active", "passive"]
    new_user_status_variants = old_user_status_variants + ["banned"]
    car_colors_variants = ["black", "white"]

    def get_database_schema(self) -> MetaData:
        return get_schema_with_enum_variants(self.old_user_status_variants)

    def get_target_schema(self) -> MetaData:
        target_schema = get_schema_with_enum_variants(self.new_user_status_variants)
        Table(
            CAR_TABLE_NAME,
            target_schema,
            Column("id", Integer, primary_key=True),
            Column(
                CAR_COLORS_COLUMN_NAME,
                postgresql.ENUM(*self.car_colors_variants, name=CAR_COLORS_ENUM_NAME),
            ),
        )
        return target_schema

    def get_expected_imports(self) -> Optional[str]:
        return expected_imports(
            f"{CAR_COLORS_ENUM_NAME} = postgresql.ENUM('black', 'white',"
            f" name='{CAR_COLORS_ENUM_NAME}', create_type=False)",
            other_imports=("from alembic_postgresql_enum import TableReference",),
        )

    def get_expected_upgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        {CAR_COLORS_ENUM_NAME}.create(op.get_bind())
        op.create_table('{CAR_TABLE_NAME}',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('{CAR_COLORS_COLUMN_NAME}', {CAR_COLORS_ENUM_NAME}, nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.sync_enum_values(
            enum_schema='public',
            enum_name='{USER_STATUS_ENUM_NAME}',
            new_values=[{', '.join(map(repr, self.new_user_status_variants))}],
            affected_columns=[TableReference(table_schema='public', table_name='{USER_TABLE_NAME}', column_name='{USER_STATUS_COLUMN_NAME}')],
            enum_values_to_rename=[],
        )
        # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> str:
        return f"""
        # ### commands auto generated by Alembic - please adjust! ###
        op.sync_enum_values(
            enum_schema='public',
            enum_name='{USER_STATUS_ENUM_NAME}',
            new_values=[{', '.join(map(repr, self.old_user_status_variants))}],
            affected_columns=[TableReference(table_schema='public', table_name='{USER_TABLE_NAME}', column_name='{USER_STATUS_COLUMN_NAME}')],
            enum_values_to_rename=[],
        )
        op.drop_table('{CAR_TABLE_NAME}')
        {CAR_COLORS_ENUM_NAME}.drop(op.get_bind())
        # ### end Alembic commands ###
        """


def test_enums_are_placed_into_template_variable(connection: "Connection", tmp_path):
    """Check that enums are defined inside ${enums} section of migration template if it has one"""
    script_directory = tmp_path / "migrations"
    (script_directory / "versions").mkdir(parents=True)
    (script_directory / "script.py.mako").write_text(
        '${imports if imports else ""}\n\nrevision = ${repr(up_revision)}\n\n${enums if enums else ""}\n'
    )

    alembic_config = AlembicConfig()
    alembic_config.set_main_option("script_location", str(script_directory))
    # template_args of alembic revision command always have config inside
    revision_template_args = {"config": alembic_config}

    old_configuration = get_configuration()
    alembic_postgresql_enum.set_configuration(Config(module_level_enums=True))
    try:
        migration_context = create_migration_context(
            connection,
            get_schema_with_enum_variants(["active", "passive"]),
            migration_options_overrides={"template_args": revision_template_args},
        )

        template_args: Dict[str, Any] = {}
        autogenerate._render_migration_diffs(migration_context, template_args)
    finally:
        alembic_postgresql_enum.set_configuration(old_configuration)

    assert revision_template_args["enums"] == definitions_block(
        f"{USER_STATUS_ENUM_NAME} = postgresql.ENUM('active', 'passive',"
        f" name='{USER_STATUS_ENUM_NAME}', create_type=False)"
    )
    # definitions are not repeated among imports
    assert template_args["imports"] == POSTGRESQL_IMPORT
    assert f"{USER_STATUS_ENUM_NAME}.create(op.get_bind())" in template_args["upgrades"]
    assert f"{USER_STATUS_ENUM_NAME}.drop(op.get_bind())" in template_args["downgrades"]


def test_enums_are_placed_among_imports_without_template_variable(connection: "Connection", tmp_path):
    """Check that enums are defined among imports if migration template has no ${enums} section"""
    script_directory = tmp_path / "migrations"
    (script_directory / "versions").mkdir(parents=True)
    (script_directory / "script.py.mako").write_text('${imports if imports else ""}\n')

    alembic_config = AlembicConfig()
    alembic_config.set_main_option("script_location", str(script_directory))
    revision_template_args = {"config": alembic_config}

    old_configuration = get_configuration()
    alembic_postgresql_enum.set_configuration(Config(module_level_enums=True))
    try:
        migration_context = create_migration_context(
            connection,
            get_schema_with_enum_variants(["active", "passive"]),
            migration_options_overrides={"template_args": revision_template_args},
        )

        template_args: Dict[str, Any] = {}
        autogenerate._render_migration_diffs(migration_context, template_args)
    finally:
        alembic_postgresql_enum.set_configuration(old_configuration)

    assert "enums" not in revision_template_args
    assert template_args["imports"] == expected_imports(
        f"{USER_STATUS_ENUM_NAME} = postgresql.ENUM('active', 'passive',"
        f" name='{USER_STATUS_ENUM_NAME}', create_type=False)"
    )


INDENTED_TEMPLATE = '''"""${message}"""

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

revision = ${repr(up_revision)}


def upgrade():
    ${enums if enums else ""}
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${enums if enums else ""}
    ${downgrades if downgrades else "pass"}
'''


def test_enums_are_indented_to_match_template(connection: "Connection", tmp_path):
    """Check that enums can be defined inside upgrade and downgrade functions"""
    script_directory = tmp_path / "migrations"
    (script_directory / "versions").mkdir(parents=True)
    (script_directory / "script.py.mako").write_text(INDENTED_TEMPLATE)

    alembic_config = AlembicConfig()
    alembic_config.set_main_option("script_location", str(script_directory))
    revision_template_args: Dict[str, Any] = {"config": alembic_config}

    old_configuration = get_configuration()
    alembic_postgresql_enum.set_configuration(Config(module_level_enums=True))
    try:
        migration_context = create_migration_context(
            connection,
            get_schema_with_enum_variants(["active", "passive"]),
            migration_options_overrides={"template_args": revision_template_args},
        )

        template_args: Dict[str, Any] = {}
        autogenerate._render_migration_diffs(migration_context, template_args)
    finally:
        alembic_postgresql_enum.set_configuration(old_configuration)

    # first line is indented by the template itself, the rest are indented by the library
    assert revision_template_args["enums"] == definitions_block(
        f"{USER_STATUS_ENUM_NAME} = postgresql.ENUM('active', 'passive',"
        f" name='{USER_STATUS_ENUM_NAME}', create_type=False)"
    ).replace("\n", "\n    ")

    migration = Template(text=INDENTED_TEMPLATE).render(
        message="test",
        up_revision="abc123",
        **revision_template_args,
        **template_args,
    )
    compile(migration, "migration.py", "exec")
